/*Write an SQL query to find out which customers have not placed any orders.*/

SELECT c.CustomerID, CONCAT(c.FirstName, ' ', c.LastName)
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE o.CustomerID IS NULL;

/*2. Write an SQL query to find the total number of products available for sale.*/

SELECT COUNT(*) AS TotalAvailableProducts 
FROM Inventory 
WHERE QuantityInStock > 0;

/*3. Write an SQL query to calculate the total revenue generated by TechShop.*/

SELECT SUM(TotalAmount) AS Total_Revenue 
FROM Orders;

SELECT SUM(od.Quantity * p.Price) AS Total_Revenue 
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID;

/*4. Write an SQL query to calculate the average quantity ordered for products in a specific category.
Allow users to input the category name as a parameter.*/

SELECT Category, (SELECT AVG(Quantity) FROM OrderDetails 
WHERE ProductID IN (SELECT ProductID FROM Products WHERE Category = 'Accessories')) AS AverageQuantityOrdered
FROM Products WHERE Category = 'Accessories' GROUP BY Category;

/*5. Write an SQL query to calculate the total revenue generated by a specific customer. Allow users
to input the customer ID as a parameter.*/

SELECT CustomerID, (SELECT SUM(TotalAmount) FROM Orders 
WHERE CustomerID = 105) AS TotalRevenue FROM Customers WHERE CustomerID = 105;

/*6. Write an SQL query to find the customers who have placed the most orders. List their names
and the number of orders they've placed.*/

SELECT CustomerID, CONCAT(FirstName, ' ', LastName) AS CustomerName, 
(SELECT COUNT(*) FROM Orders O WHERE O.CustomerID = C.CustomerID) AS TotalOrders 
FROM Customers C WHERE CustomerID IN (SELECT CustomerID FROM Orders GROUP BY CustomerID ORDER BY COUNT(*) DESC LIMIT 1);

/*7. Write an SQL query to find the most popular product category, which is the one with the highest
total quantity ordered across all orders.*/

SELECT Category, TotalQuantityOrdered FROM (SELECT P.Category, SUM(OD.Quantity) AS TotalQuantityOrdered FROM OrderDetails OD
JOIN Products P ON OD.ProductID = P.ProductID GROUP BY P.Category) AS CategoryOrders
ORDER BY TotalQuantityOrdered DESC LIMIT 1;

/*8. Write an SQL query to find the customer who has spent the most money (highest total revenue)
on electronic gadgets. List their name and total spending.*/

SELECT CONCAT(C.FirstName, ' ', C.LastName) AS CustomerName, O.TotalAmount AS TotalRevenue FROM Orders O
JOIN Customers C ON O.CustomerID = C.CustomerID WHERE O.TotalAmount = (SELECT MAX(TotalAmount) FROM Orders);

/*9. Write an SQL query to calculate the average order value (total revenue divided by the number of
orders) for all customers.*/

SELECT C.CustomerID, CONCAT(C.FirstName, ' ', C.LastName) AS CustomerName,
(SELECT SUM(O.TotalAmount) FROM Orders O WHERE O.CustomerID = C.CustomerID) / 
(SELECT COUNT(O.OrderID) FROM Orders O WHERE O.CustomerID = C.CustomerID) 
AS AverageOrderValue FROM Customers C;

/*10. Write an SQL query to find the total number of orders placed by each customer and list their
names along with the order count.*/

SELECT C.CustomerID, CONCAT(C.FirstName, ' ', C.LastName) AS CustomerName,
(SELECT COUNT(O.OrderID) FROM Orders O WHERE O.CustomerID = C.CustomerID) AS TotalOrders FROM Customers C;



